# Generated by Django 4.1.7 on 2023-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.TextField(verbose_name='中文')),
                ('french', models.TextField(verbose_name='法语')),
                ('similar', models.TextField(verbose_name='类似表达')),
                ('source', models.CharField(max_length=128, verbose_name='来源')),
                ('definition', models.TextField(verbose_name='定义')),
                ('example', models.TextField(verbose_name='例句')),
                ('cata', models.SmallIntegerField(choices=[(1, '其他词汇'), (2, '决策部署'), (3, '防控救治'), (4, '专有名词'), (5, '机构场所'), (6, '社会生活')], verbose_name='分类')),
                ('tag', models.CharField(max_length=32, verbose_name='标签')),
            ],
        ),
    ]
